import {
  BadgeDollarSign,
  BedDouble,
  BookCopy,
  BookOpenCheck,
  Building2,
  CalendarCheck2,
  CircleDollarSign,
  ClipboardCheck,
  ContactRound,
  DoorOpen,
  FileCheck2,
  GraduationCap,
  HandCoins,
  Landmark,
  ListChecks,
  NotebookTabs,
  School,
  Settings2,
  UserCheck,
  UsersRound,
} from "lucide-react";

const tones = ["bg-info/10 text-info", "bg-success/10 text-success", "bg-warning/10 text-warning", "bg-primary/10 text-primary"];

export const modules = {
  academics: {
    icon: BookCopy,
    eyebrow: "تعلیمی انتظام",
    title: "تعلیمی امور",
    description: "شعبوں، جماعتوں، مضامین اور تعلیمی سرگرمیوں کا انتظام کریں۔",
    actionLabel: "نئی جماعت شامل کریں",
    stats: [
      { label: "کل شعبے", value: "6", detail: "فعال شعبے", icon: Building2, tone: "info" },
      { label: "جماعتیں", value: "18", detail: "تمام درجات", icon: School, tone: "success" },
      { label: "مضامین", value: "34", detail: "زیر تدریس", icon: NotebookTabs, tone: "warning" },
      { label: "آج کی کلاسیں", value: "42", detail: "شیڈول شدہ", icon: CalendarCheck2, tone: "primary" },
    ],
    recordsTitle: "آج کی کلاسیں",
    recordsDescription: "آج کے اہم تعلیمی شیڈول",
    records: [
      { title: "حفظ اول", subtitle: "تجوید — قاری عبدالرحمن", meta: "09:00 صبح", tone: tones[0] },
      { title: "درجہ ثالثہ", subtitle: "فقہ — مولانا بلال", meta: "10:30 صبح", tone: tones[1] },
      { title: "ناظرہ", subtitle: "قرآنِ کریم — قاری عثمان", meta: "12:00 دوپہر", tone: tones[2] },
    ],
    summaryTitle: "شعبہ وار کارکردگی",
    summaryDescription: "اس ماہ کی تعلیمی تکمیل",
    summaryItems: [
      { label: "شعبہ حفظ", value: "88٪", progress: 88, tone: "bg-success" },
      { label: "درسِ نظامی", value: "76٪", progress: 76, tone: "bg-info" },
      { label: "ناظرہ", value: "92٪", progress: 92, tone: "bg-warning" },
    ],
  },
  exams: {
    icon: FileCheck2,
    eyebrow: "امتحانات و نتائج",
    title: "امتحانات و نتائج",
    description: "داخلی امتحانات، وفاق رجسٹریشن اور طلبہ کے نتائج ایک جگہ منظم کریں۔",
    actionLabel: "نیا امتحان بنائیں",
    stats: [
      { label: "آنے والے امتحانات", value: "6", detail: "اس ماہ", icon: CalendarCheck2, tone: "info" },
      { label: "رجسٹرڈ طلبہ", value: "628", detail: "تمام امتحانات", icon: UsersRound, tone: "success" },
      { label: "جاری شدہ نتائج", value: "4", detail: "اس سیشن", icon: FileCheck2, tone: "warning" },
      { label: "کامیابی کی شرح", value: "92٪", detail: "حالیہ نتیجہ", icon: GraduationCap, tone: "primary" },
    ],
    recordsTitle: "امتحانی شیڈول",
    recordsDescription: "آنے والے امتحانات اور اہم تفصیلات",
    records: [
      { title: "ماہانہ حفظ امتحان", subtitle: "حفظ اول تا حفظ سوم", meta: "28 اگست", tone: tones[1] },
      { title: "درجہ ثالثہ امتحان", subtitle: "فقہ اور اصول الفقہ", meta: "30 اگست", tone: tones[0] },
      { title: "وفاق تیاری ٹیسٹ", subtitle: "درجہ عالمیہ", meta: "02 ستمبر", tone: tones[2] },
    ],
    summaryTitle: "حالیہ نتائج",
    summaryDescription: "جماعت وار کامیابی کی شرح",
    summaryItems: [
      { label: "حفظ اول", value: "96٪", progress: 96, tone: "bg-success" },
      { label: "درجہ ثالثہ", value: "89٪", progress: 89, tone: "bg-info" },
      { label: "ناظرہ", value: "94٪", progress: 94, tone: "bg-warning" },
    ],
  },
  hifz: {
    icon: GraduationCap,
    eyebrow: "حفظ و ناظرہ",
    title: "حفظ و ناظرہ",
    description: "سبق، سبقی، منزل اور طالب علموں کی یومیہ پیش رفت کا جائزہ لیں۔",
    actionLabel: "نیا ڈائری لاگ",
    stats: [
      { label: "فعال طلبہ", value: "173", detail: "شعبہ حفظ", icon: UsersRound, tone: "info" },
      { label: "آج کا سبق", value: "148", detail: "لاگ مکمل", icon: BookOpenCheck, tone: "success" },
      { label: "تصدیق درکار", value: "12", detail: "استاد کے پاس", icon: FileCheck2, tone: "warning" },
      { label: "اوسط پیش رفت", value: "74٪", detail: "اس ماہ", icon: GraduationCap, tone: "primary" },
    ],
    recordsTitle: "تازہ حفظ ڈائری",
    recordsDescription: "آج کی تازہ اندراجات",
    records: [
      { title: "عبداللہ صدیق", subtitle: "سورۃ النساء — سبق مکمل", meta: "10 منٹ پہلے", tone: tones[1] },
      { title: "محمد طلحہ", subtitle: "سورۃ آل عمران — سبقی", meta: "22 منٹ پہلے", tone: tones[0] },
      { title: "زینب فاطمہ", subtitle: "سورۃ البقرہ — منزل", meta: "35 منٹ پہلے", tone: tones[2] },
    ],
    summaryTitle: "آج کا ہدف",
    summaryDescription: "روزانہ کے حفظ اہداف کی تکمیل",
    summaryItems: [
      { label: "نیا سبق", value: "86٪", progress: 86, tone: "bg-success" },
      { label: "سبقی", value: "72٪", progress: 72, tone: "bg-info" },
      { label: "منزل", value: "64٪", progress: 64, tone: "bg-warning" },
    ],
  },
  attendance: {
    icon: ClipboardCheck,
    eyebrow: "حاضری کا انتظام",
    title: "حاضری",
    description: "روزانہ طلبہ اور عملے کی حاضری، رخصت اور غیر حاضری کا ریکارڈ۔",
    actionLabel: "حاضری لگائیں",
    stats: [
      { label: "آج حاضر", value: "1,106", detail: "کل طلبہ کا 88.6٪", icon: UserCheck, tone: "success" },
      { label: "غیر حاضر", value: "142", detail: "مزید جائزہ", icon: ContactRound, tone: "destructive" },
      { label: "رخصت پر", value: "18", detail: "منظور شدہ", icon: CalendarCheck2, tone: "warning" },
      { label: "مکمل جماعتیں", value: "16/18", detail: "آج کی رپورٹ", icon: ListChecks, tone: "primary" },
    ],
    recordsTitle: "جماعت وار حاضری",
    recordsDescription: "آج کی تازہ ترین رپورٹ",
    records: [
      { title: "حفظ اول", subtitle: "68 میں سے 64 طلبہ حاضر", meta: "94٪", tone: tones[1] },
      { title: "درجہ ثالثہ", subtitle: "53 میں سے 47 طلبہ حاضر", meta: "89٪", tone: tones[0] },
      { title: "ناظرہ", subtitle: "82 میں سے 71 طلبہ حاضر", meta: "87٪", tone: tones[2] },
    ],
    summaryTitle: "ہفتہ وار حاضری",
    summaryDescription: "گزشتہ سات دن کی مجموعی شرح",
    summaryItems: [
      { label: "پیر", value: "91٪", progress: 91, tone: "bg-success" },
      { label: "بدھ", value: "88٪", progress: 88, tone: "bg-info" },
      { label: "جمعہ", value: "86٪", progress: 86, tone: "bg-warning" },
    ],
  },
  hostel: {
    icon: BedDouble,
    eyebrow: "ہاسٹل / دارالاقامہ",
    title: "ہاسٹل",
    description: "رہائشی کمرے، الاٹمنٹ، گیٹ پاس اور دارالاقامہ کی روزمرہ معلومات۔",
    actionLabel: "کمرہ الاٹ کریں",
    stats: [
      { label: "کل کمرے", value: "64", detail: "3 ونگز", icon: Building2, tone: "info" },
      { label: "مقیم طلبہ", value: "418", detail: "مکمل الاٹمنٹ", icon: BedDouble, tone: "success" },
      { label: "خالی بسترے", value: "26", detail: "دستیاب", icon: DoorOpen, tone: "warning" },
      { label: "فعال گیٹ پاس", value: "9", detail: "آج کے لیے", icon: ClipboardCheck, tone: "primary" },
    ],
    recordsTitle: "حالیہ الاٹمنٹ",
    recordsDescription: "رہائشی طلبہ کی تازہ تبدیلیاں",
    records: [
      { title: "احمد رضا", subtitle: "ونگ الف — کمرہ 12", meta: "آج", tone: tones[1] },
      { title: "عائشہ نور", subtitle: "ونگ ب — کمرہ 08", meta: "آج", tone: tones[0] },
      { title: "محمد زبیر", subtitle: "ونگ الف — کمرہ 14", meta: "کل", tone: tones[2] },
    ],
    summaryTitle: "ونگ کی گنجائش",
    summaryDescription: "ہر ونگ میں بستروں کی دستیابی",
    summaryItems: [
      { label: "ونگ الف", value: "94٪ بھر چکا", progress: 94, tone: "bg-success" },
      { label: "ونگ ب", value: "88٪ بھر چکا", progress: 88, tone: "bg-info" },
      { label: "ونگ ج", value: "76٪ بھر چکا", progress: 76, tone: "bg-warning" },
    ],
  },
  finance: {
    icon: BadgeDollarSign,
    eyebrow: "مالیاتی انتظام",
    title: "مالیات",
    description: "فیس، عطیات، اسپانسرشپ اور مدرسہ کے اخراجات کا مکمل ریکارڈ۔",
    actionLabel: "نئی وصولی",
    stats: [
      { label: "اس ماہ کی وصولی", value: "845,000", detail: "روپے", icon: CircleDollarSign, tone: "success" },
      { label: "اس ماہ اخراجات", value: "321,000", detail: "روپے", icon: Landmark, tone: "destructive" },
      { label: "فعال عطیہ دہندگان", value: "84", detail: "اس ماہ", icon: HandCoins, tone: "info" },
      { label: "بقایا فیس", value: "176,000", detail: "روپے", icon: BadgeDollarSign, tone: "warning" },
    ],
    recordsTitle: "حالیہ لین دین",
    recordsDescription: "تازہ وصولیوں اور اخراجات کا خلاصہ",
    records: [
      { title: "فیس وصولی", subtitle: "رسید #F-2048", meta: "245,000 روپے", tone: tones[1] },
      { title: "راشن کی خریداری", subtitle: "خرچ نمبر #E-104", meta: "48,500 روپے", tone: tones[2] },
      { title: "عطیہ موصول", subtitle: "عطیہ دہندہ: محمد علی", meta: "100,000 روپے", tone: tones[0] },
    ],
    summaryTitle: "ماہانہ بجٹ",
    summaryDescription: "اہم فنڈز کی استعمال شدہ رقم",
    summaryItems: [
      { label: "تعلیمی فنڈ", value: "84٪", progress: 84, tone: "bg-success" },
      { label: "ہاسٹل فنڈ", value: "67٪", progress: 67, tone: "bg-info" },
      { label: "زکوٰۃ فنڈ", value: "53٪", progress: 53, tone: "bg-warning" },
    ],
  },
  settings: {
    icon: Settings2,
    eyebrow: "سسٹم ترتیبات",
    title: "ترتیبات",
    description: "مدرسہ کی بنیادی معلومات، تعلیمی سال اور نظام کی ترجیحات ترتیب دیں۔",
    actionLabel: "ترتیبات محفوظ کریں",
    stats: [
      { label: "فعال صارفین", value: "14", detail: "اس مہینے", icon: UsersRound, tone: "info" },
      { label: "صارف کردار", value: "5", detail: "اجازتیں", icon: Settings2, tone: "success" },
      { label: "تعلیمی سال", value: "1448", detail: "ہجری", icon: CalendarCheck2, tone: "warning" },
      { label: "بیک اپ", value: "آج", detail: "آخری بیک اپ", icon: FileCheck2, tone: "primary" },
    ],
    recordsTitle: "حالیہ تبدیلیاں",
    recordsDescription: "ترتیبات میں کی گئی تازہ تبدیلیاں",
    records: [
      { title: "تعلیمی سال اپ ڈیٹ", subtitle: "1448ھ بطور فعال سال مقرر", meta: "آج", tone: tones[1] },
      { title: "نیا صارف شامل", subtitle: "عملہ کے لیے استاد کا کردار", meta: "کل", tone: tones[0] },
      { title: "فیس کی ترتیب تبدیل", subtitle: "درجہ ثالثہ کی ماہانہ فیس", meta: "2 دن پہلے", tone: tones[2] },
    ],
    summaryTitle: "سسٹم کی تکمیل",
    summaryDescription: "بنیادی نظام کی ترتیبات کی حالت",
    summaryItems: [
      { label: "مدرسہ پروفائل", value: "100٪", progress: 100, tone: "bg-success" },
      { label: "تعلیمی ڈھانچہ", value: "92٪", progress: 92, tone: "bg-info" },
      { label: "صارف اجازتیں", value: "78٪", progress: 78, tone: "bg-warning" },
    ],
  },
};
